### ISSUE TITLE
Can't use lcfg in a release

### ISSUE THREAD

**Issue by yurrriq** [lfex/lcfg#14]
(Ticket description re-written by @oubiwann; original content has been moved below, to the next comment in this ticket.)

Due to the fact that `lfetool` is no longer used in the tool chain, lcfg's `app.src` file is no longer being generated. As such, logjam, which depends upon the log configuration parsing of the `lfe.config` file provided by `lcfg`, cannot currently be built without error.

Proposed solution:
* [x]  Quick-fix this to get logjam building again (see #16)
* [ ]  Update the `lfe-rebar3/compile` plugin to build all the necessary Erlang files from `lfe.config` prior to compiling (see https://github.com/lfe-rebar3/compile/issues/27)
* [ ]  Move log-specific parsing out of lcfg and into logjam (see https://github.com/lfex/logjam/issues/6 and #17)
* [x]  Get ljson tests passing again (see https://github.com/lfex/ljson/issues/6)

By addressing the first bullet, this ticket will be resolved. Longer-term and better solutions will be provided by the tickets in the subsequent bullets.

**Comment by yurrriq** [comment]
It also seems the `compile-app-src` make target is gone.

**Comment by yurrriq** [comment]
Bump. I'm trying to use logjam in a release again I'm still running into this error.

**Comment by yurrriq** [comment]
I've come up with a hacky workaround, but still need to manually specify `lutil` as a dependency... If I submit a patch that makes `lcfg` play nice with `rebar3` will you consider merging it?

**Comment by yurrriq** [comment]
I've decided just to use lager directly and avoid all this. Below are my hacks, for posterity.

---

**bin/lcfg-hack**:

``` lfe
#!/usr/bin/env lfe
;; -*- mode: lfe -*-

;; Pretend like we're rebar3
(io:put_chars (color:green "===> Generating lcfg.app...\n"))

;; Ensure the required modules are loaded.
(lists:foreach #'code:ensure_loaded/1 '[lcfg-appsrc lcfg-proj lcfg lcfg-util])

;; Change the working directory to the lcfg root
(cd (filename:join (os:getenv "REBAR_DEPS_DIR") "lcfg"))

;; Read lcfg's lfe.config and generate lcfg.app in lcfg/ebin
(let* ((`#(ok ,lfe-config) (lfe_io:read_file "lfe.config"))
       (config             (lcfg-appsrc:get-data lfe-config)))
  ;; If we're in DEBUG mode, print the contents of lcfg.app
  (case (os:getenv "DEBUG")
    ("1" (io:format (color:cyan (io_lib:format "\n     ~p\n\n" `[,config]))))
    (_   'ok))
  (lcfg-appsrc:write config "ebin/lcfg.app"))
```

**rebar.config**:

``` erlang
%% Note this assumes lfe as a dependency. Could use just "lfe" too.
{pre_hooks, [
  {release, "$REBAR_DEPS_DIR/lfe/bin/lfe bin/lcfg-hack"}
]}.
```

**Comment by oubiwann** [comment]
Yeah, this bit of functionality is now missing since `lfetool` is no longer part of the tool chain (it used to do this).

What needs to happen is for the lfe-rebar3/compile plugin to handle this. I've just opened a couple of related tickets:
- [ ] https://github.com/lfe-rebar3/compile/issues/27
- [x] #16

**Comment by yurrriq** [comment]
The `app_compile` hook might be useful here too.

**Comment by oubiwann** [comment]
Okay, the issue of not being able to use logjam in a release should now be fixed. I haven't tested making a release, but it's now got a regular app.src and is published on Hex.pm.

If this fix works, feel free to close this ticket.

The other tickets mentioned here address some of the underlying root issues around why logjam wasn't originally usable in a release.

**Comment by yurrriq** [comment]
Sounds great! I might be able to try it out today, otherwise Tuesday.

**Comment by oubiwann** [comment]
Note: renamed this ticket to be lcfg, since it's in the lcfg project. I've just created an ljson ticket which will go the rest of the way towards addressing the original title of this ticket (fixing ljson will allow logjam to be used in a release):
* [x] https://github.com/lfex/ljson/issues/6
